Dialogue.New("Doug3_1", "Douglass", 1, "So like uh- what- what type of coffee did you get?",60,"Doug3_2",true)
Dialogue.New("Doug3_2", "Lorelai", 1, "I just got a cappuccino. I think they taste good.",60,"Doug3")

Dialogue.New("Doug3_1_1_1", "Douglass", 1, "So like uh- what- what type of coffee did you get?",60,"Doug3_1_1_2",true)
Dialogue.New("Doug3_1_1_2", "Douglass", 1, "So like uh- what- what type of coffee did you get?",60,"Doug3_1_1_2",true)

Dialogue.New("Doug3_1_2_1", "Douglass", 1, "So like uh- what- what type of coffee did you get?",60,"Doug3_1_2_2",true)
Dialogue.New("Doug3_1_2_2", "Douglass", 1, "So like uh- what- what type of coffee did you get?",60,"Doug3_1_2_3",true)
Dialogue.New("Doug3_1_2_3", "Douglass", 1, "So like uh- what- what type of coffee did you get?",60,"Doug3_1_2_4",true)
Dialogue.New("Doug3_1_2_4", "Douglass", 1, "So like uh- what- what type of coffee did you get?",60,"Doug3_1_2_5",true)
Dialogue.New("Doug3_1_2_5", "Douglass", 1, "So like uh- what- what type of coffee did you get?",60,"Doug3_1_2_2",true)

Dialogue.New("Doug3_1_3_1", "Douglass", 1, "So like uh- what- what type of coffee did you get?",60,"Doug3_1_3_2",true)
Dialogue.New("Doug3_1_3_2", "Douglass", 1, "So like uh- what- what type of coffee did you get?",60,"Doug3_1_3_3",true)
Dialogue.New("Doug3_1_3_3", "Douglass", 1, "So like uh- what- what type of coffee did you get?",60,"Doug3_1_3_4",true)
Dialogue.New("Doug3_1_3_4", "Douglass", 1, "So like uh- what- what type of coffee did you get?",60,"Doug3_1_3_5",true)
Dialogue.New("Doug3_1_3_5", "Douglass", 1, "So like uh- what- what type of coffee did you get?",60,"Doug3_1_3_6",true)
Dialogue.New("Doug3_1_3_6", "Douglass", 1, "So like uh- what- what type of coffee did you get?",60,"Doug3_1_3_7",true)
Dialogue.New("Doug3_1_3_7", "Douglass", 1, "So like uh- what- what type of coffee did you get?",60,"Doug3_1_3_8",true)
Dialogue.New("Doug3_1_3_8", "Douglass", 1, "So like uh- what- what type of coffee did you get?",60,"Doug3_1_3_9",true)
Dialogue.New("Doug3_1_3_9", "Douglass", 1, "So like uh- what- what type of coffee did you get?",60,"Doug3_1_3_10",true)
Dialogue.New("Doug3_1_3_10", "Douglass", 1, "So like uh- what- what type of coffee did you get?",60,"Doug3_1_3_11",true)
Dialogue.New("Doug3_1_3_11", "Douglass", 1, "So like uh- what- what type of coffee did you get?",60,"Doug3_1_3_12",true)
Dialogue.New("Doug3_1_3_12", "Douglass", 1, "So like uh- what- what type of coffee did you get?",60,"Doug3_1_3_13",true)
Dialogue.New("Doug3_1_3_13", "Douglass", 1, "So like uh- what- what type of coffee did you get?",60,"Doug3_1_3_14",true)
Dialogue.New("Doug3_1_3_14", "Douglass", 1, "So like uh- what- what type of coffee did you get?",60,"Doug3_1_3_15",true)
Dialogue.New("Doug3_1_3_15", "Douglass", 1, "So like uh- what- what type of coffee did you get?",60,"Doug3_1_3_2",true)

Dialogue.New("Doug3_1_4_1", "Douglass", 1, "So like uh- what- what type of coffee did you get?",60,"Doug3_1_4_2",true)
Dialogue.New("Doug3_1_4_2", "Douglass", 1, "So like uh- what- what type of coffee did you get?",60,"Doug3_1_4_3",true)
Dialogue.New("Doug3_1_4_3", "Douglass", 1, "So like uh- what- what type of coffee did you get?",60,"Doug3_1_4_4",true)
Dialogue.New("Doug3_1_4_4", "Douglass", 1, "So like uh- what- what type of coffee did you get?",60,"Doug3_1_4_5",true)
Dialogue.New("Doug3_1_4_5", "Douglass", 1, "So like uh- what- what type of coffee did you get?",60,"Doug3_1_4_2",true)