Dialogue.New("Tree_3", "Douglass", 2, "So like uh- what- what type of coffee did you get?",60,"Tree_3_2",true)
Dialogue.New("Tree_3_2", "Lorelai", 2, "I just got a cappuccino. I think they taste good.",60,"Choice_5")

Dialogue.New("Tree_3_Red_1", "Lorelai", 7, "You think you'll taste just as good as the cappuccino?",60,"Tree_3_Red_2",true)
Dialogue.New("Tree_3_Red_2", "Douglass", 2, "What? Like uh.. You mean if my coffee tastes just as good?",60,"Choice_6")

Dialogue.New("Tree_3_Red_2_Branch_1_1", "Lorelai", 7, "I meant your lips. Like do your lips taste good.",60,"Tree_3_Red_2_Branch_1_2",true)
Dialogue.New("Tree_3_Red_2_Branch_1_2", "Douglass", 2, "Oh! uh- … what?",60,"Tree_3_Red_2_Branch_1_3",true)
Dialogue.New("Tree_3_Red_2_Branch_1_3", "Lorelai", 7, "Yeah.  You want a kiss?",60,"Tree_3_Red_2_Branch_1_4",true)
Dialogue.New("Tree_3_Red_2_Branch_1_4", "Douglass", 2, "..Later. Uh- Maybe.",60,"Good_1",true)

Dialogue.New("Tree_3_Red_2_Branch_2_1", "Lorelai", 7, "I meant your lips. Like do your lips taste good.",60,"Tree_3_Red_2_Branch_2_2",true)
Dialogue.New("Tree_3_Red_2_Branch_2_2", "Douglass", 2, "Oh! uh- … what?",60,"Tree_3_Red_2_Branch_2_3",true)
Dialogue.New("Tree_3_Red_2_Branch_2_3", "Lorelai", 7, "Yeah.  You want a kiss?",60,"Tree_3_Red_2_Branch_2_4",true)
Dialogue.New("Tree_3_Red_2_Branch_2_4", "Douglass", 2, "....",60,"Neutral_1",true)

Dialogue.New("Tree_3_Red_2_Branch_3_1", "Lorelai", 7, "Yeah. your coffee. Do you think it's good?",60,"Tree_3_Red_2_Branch_3_2",true)
Dialogue.New("Tree_3_Red_2_Branch_3_2", "Douglass", 7, "Yeah.. yeah. I like it a lot. I don't know if like-",60,"Tree_3_Red_2_Branch_3_3",true)
Dialogue.New("Tree_3_Red_2_Branch_3_3", "Douglass", 7, "Better than what you have. I never tried it.",60,"Tree_3_Red_2_Branch_3_4",true)
Dialogue.New("Tree_3_Red_2_Branch_3_4", "Lorelai", 2, "Makes sense.",60,"Bad_1",true)

Dialogue.New("Tree_3_Green_1", "Lorelai", 2, "What kind of coffee did you get?",60,"Tree_3_Green_2",true)
Dialogue.New("Tree_3_Green_2", "Douglass", 2, "Oh. Oh- this? It's.. a double chocolate chip frappuccino. 75% sweet. Oat milk. And uh-",60,"Tree_3_Green_3",true)
Dialogue.New("Tree_3_Green_3", "Douglass", 2, "Extra whipped cream. I-I mean I never really got this before- just heard it was good.",60,"Tree_3_Green_4",true)
Dialogue.New("Tree_3_Green_4", "Lorelai", 6, "You seem like you've had it before.",60,"Tree_3_Green_5",true)
Dialogue.New("Tree_3_Green_5", "Douglass", 2, ".. Oh! Oh no- no I just.. yeah. A recommendation. From like- the.. worker. I guess.",60,"Choice_7")

Dialogue.New("Tree_3_Green_5_Branch_1_1", "Lorelai", 2, "No- no I mean.. I feel like most people don't even remember the order if they get a new drink.",60,"Tree_3_Green_5_Branch_1_2",true)
Dialogue.New("Tree_3_Green_5_Branch_1_2", "Lorelai", 5, "Just say you get it like all the time. Not really a reason to lie.",60,"Tree_3_Green_5_Branch_1_3",true)
Dialogue.New("Tree_3_Green_5_Branch_1_3", "Douglass", 2, ".. Uh.. Yeah. I had it a few times.",60,"Tree_3_Green_5_Branch_1_4",true)
Dialogue.New("Tree_3_Green_5_Branch_1_4", "Lorelai", 2, "See? It's that easy.",60,"Tree_3_Green_5_Branch_1_5",true)
Dialogue.New("Tree_3_Green_5_Branch_1_5", "Douglass", 2, "...",60,"Neutral_1",true)

Dialogue.New("Tree_3_Green_5_Branch_2_1", "Lorelai", 2, "No- no I mean.. I feel like most people don't even remember the order if they get a new drink.",60,"Tree_3_Green_5_Branch_2_2",true)
Dialogue.New("Tree_3_Green_5_Branch_2_2", "Lorelai", 2, "But you're cute when you lie so I'll let it slide for now.",60,"Tree_3_Green_5_Branch_2_3",true)
Dialogue.New("Tree_3_Green_5_Branch_2_3", "Douglass", 2, "..What? I-I'm not lying I-",60,"Tree_3_Green_5_Branch_2_4",true)
Dialogue.New("Tree_3_Green_5_Branch_2_4", "Lorelai", 2, "See? Cute.",60,"Tree_3_Green_5_Branch_2_5",true)
Dialogue.New("Tree_3_Green_5_Branch_2_5", "Douglass", 2, "...",60,"Good_1",true)

Dialogue.New("Tree_3_Green_5_Branch_3_1", "Douglass", 2, "Yeah. Well I'm glad you like it then.",60,"Tree_3_Green_5_Branch_3_2",true)
Dialogue.New("Tree_3_Green_5_Branch_3_2", "Douglass", 2, "It's really good. You should try it sometime.",60,"Tree_3_Green_5_Branch_3_3",true)
Dialogue.New("Tree_3_Green_5_Branch_3_3", "Douglass", 2, "I guess I should. You definitely seem like a fan.",60,"Tree_3_Green_5_Branch_3_4",true)
Dialogue.New("Tree_3_Green_5_Branch_3_4", "Douglass", 2, "..Yeah.",60,"Tree_4",true)

Dialogue.New("Tree_3_Blue_1", "Lorelai", 2, "Yeah, I always get cappuccinos. It's like- the perfect balance of milk and coffee.",60,"Tree_3_Blue_2",true)
Dialogue.New("Tree_3_Blue_2", "Douglass", 2, "Really?",60,"Tree_3_Blue_3",true)
Dialogue.New("Tree_3_Blue_3", "Lorelai", 2, "Yeah, it's also great for eight AMs-",60,"Tree_3_Blue_4",true)
Dialogue.New("Tree_3_Blue_4", "Lorelai", 2, "And you can make super cute art shit with the milk foam!",60,"Tree_3_Blue_5",true)
Dialogue.New("Tree_3_Blue_5", "Lorelai", 2, "Honestly, I don't even know why other people order other coffees.",60,"Tree_3_Blue_6",true)
Dialogue.New("Tree_3_Blue_6", "Douglass", 2, "Wow uh.. Tha-",60,"Tree_3_Blue_7",true)
Dialogue.New("Tree_3_Blue_7", "Lorelai", 3, "Yeah. Yeah I REALLY like cappuccinos. I mean the fact that it's also like a form of art.",60,"Tree_3_Blue_8",true)
Dialogue.New("Tree_3_Blue_8", "Douglass", 2, "Wel-",60,"Tree_3_Blue_9",true)
Dialogue.New("Tree_3_Blue_9", "Lorelai", 2, "And that it's so customizable to what you enjoy, and what you're interested in.",60,"Tree_3_Blue_10",true)
Dialogue.New("Tree_3_Blue_10", "Lorelai", 2, "It's just such a perfect drink. You know?",60,"Tree_3_Blue_11",true)
Dialogue.New("Tree_3_Blue_11", "Douglass", 2, "Ah, yeah.",60,"Tree_3_Blue_12",true)
Dialogue.New("Tree_3_Blue_12", "Lorelai", 2, "I think that any sane person understands why cappuccinos are so popular.",60,"Tree_3_Blue_13",true)
Dialogue.New("Tree_3_Blue_13", "Lorelai", 2, "Are you sane?",60,"Tree_3_Blue_14",true)
Dialogue.New("Tree_3_Blue_14", "Douglass", 2, "I think so. Uh.",60,"Tree_3_Blue_15",true)
Dialogue.New("Tree_3_Blue_15", "Lorelai", 2, "That's good.",60,"Neutral_1",true)

Dialogue.New("Tree_3_Purple_1", "Lorelai", 2, "Do you like coffee? You.. seem to be liking your drink a lot.",60,"Tree_3_Purple_2",true)
Dialogue.New("Tree_3_Purple_2", "Douglass", 2, "Yeah. It's a double chocolate frap. Really good. And it keeps me awake",60,"Tree_3_Purple_3",true)
Dialogue.New("Tree_3_Purple_3", "Douglass", 2, "For when I have to stay up really late to study.",60,"Tree_3_Purple_5",true)
Dialogue.New("Tree_3_Purple_5", "Lorelai", 2, "You study a lot?",60,"Tree_3_Purple_5",true)
Dialogue.New("Tree_3_Purple_5", "Douglass", 2, "Yeah. Yeah- especially Organic Chemistry. Class sucks.",60,"Tree_3_Purple_5_Branch_2_1",true)

Dialogue.New("Tree_3_Purple_5_Branch_1_1", "Lorelai", 2, "We should study together some time. I mean we're in the same class after all.",60,"Tree_3_Purple_5_Branch_1_2",true)
Dialogue.New("Tree_3_Purple_5_Branch_1_2", "Douglass", 2, "..Really? You'd want to?",60,"Tree_3_Purple_5_Branch_1_3",true)
Dialogue.New("Tree_3_Purple_5_Branch_1_3", "Lorelai", 2, "Why not?",60,"Tree_3_Purple_5_Branch_1_4",true)
Dialogue.New("Tree_3_Purple_5_Branch_1_4", "Douglass", 2, "Yeah.. Yeah alright.",60,"Tree_3_Purple_5_Branch_2_1",true)

Dialogue.New("Tree_3_Purple_5_Branch_2_1", "Lorelai", 2, "We should study together some time. I mean we're in the same class after all.",60,"Tree_3_Purple_5_Branch_2_2",true)
Dialogue.New("Tree_3_Purple_5_Branch_2_2", "Douglass", 2, "..Really? You'd want to?",60,"Tree_3_Purple_5_Branch_2_3",true)
Dialogue.New("Tree_3_Purple_5_Branch_2_3", "Lorelai", 2, "Why not?",60,"Tree_3_Purple_5_Branch_2_4",true)
Dialogue.New("Tree_3_Purple_5_Branch_2_4", "Douglass", 2, "Yeah.. Yeah alright.",60,"Tree_3_Purple_5_Branch_2_5",true)
Dialogue.New("Tree_3_Purple_5_Branch_2_5", "Lorelai", 7, "So we're gonna see the Godfather and study together?",60,"Tree_3_Purple_5_Branch_2_6",true)
Dialogue.New("Tree_3_Purple_5_Branch_2_6", "Douglass", 2, "If uh.. If thats not too much. Is it?",60,"Tree_3_Purple_5_Branch_2_7",true)
Dialogue.New("Tree_3_Purple_5_Branch_2_7", "Lorelai", 2, "Of course not. You're too cute not to see again.",60,"Good_1",true)

Dialogue.New("Tree_3_Purple_5_Branch_3_1", "Lorelai", 2, "I think what we're learning is interesting, but like.. man. Hard class.",60,"Tree_3_Purple_5_Branch_3_2",true)
Dialogue.New("Tree_3_Purple_5_Branch_3_2", "Douglass", 6, "I get it. Theres.. A lot. To memorize. I mean like stereochemistry too-",60,"Tree_3_Purple_5_Branch_3_3",true)
Dialogue.New("Tree_3_Purple_5_Branch_3_3", "Lorelai", 2, "Oh yeah. I struggled a lot with that.",60,"Tree_3_Purple_5_Branch_3_4",true)
Dialogue.New("Tree_3_Purple_5_Branch_3_4", "Douglass", 2, "Me too.",60,"Doug4",true)