Dialogue.New("Doug2", "Douglass", 1, "Oh, really? Wow, that uh- that's pretty cool. I mean I watch a lot of movies. And films.",60,"Doug2")

Dialogue.New("Doug2_1_1", "Douglass", 1, "I watch a lot of PC movies. Like uh.. Puperman. And Patman- yeah. ",60,"Doug2_1_2",true)
Dialogue.New("Doug2_1_2", "Lorelai", 1, "My brother likes a lot of superhero shit.",60,"Doug2_1_3",true)
Dialogue.New("Doug2_1_3", "Douglass", 1, "Your brother?",60,"Doug2_1_4",true)
Dialogue.New("Doug2_1_4", "Lorelai", 1, "Yeah. He's five.",60,"Doug2_1_5",true)
Dialogue.New("Doug2_1_5", "Douglass", 1, "Oh.",60,"Doug2_1_6",true)
Dialogue.New("Doug2_1_6", "Lorelai", 1, "No but Superheroes are pretty cool. I mean they're all about justice. Seems cool.",60,"Doug3_1")

Dialogue.New("Doug2_2_1", "Douglass", 1, "So. What types of movies do you like?",60,"Doug2_2_2",true)
Dialogue.New("Doug2_2_2", "Lorelai", 1, "You ever heard of the Godfather?",60,"Doug2_2_3",true)
Dialogue.New("Doug2_2_3", "Douglass", 1, "Uh.. no. I don't- probably not.",60,"Doug2_2_4",true)
Dialogue.New("Doug2_2_4", "Lorelai", 1, "Well its cinematography is the best. Not even kidding.",60,"Doug2_2_5",true)
Dialogue.New("Doug2_2_5", "Douglass", 1, "They do a bunch of different scene and perspective changing, I mean-",60,"Doug2_2_6",true)
Dialogue.New("Doug2_2_6", "Lorelai", 1, "You just have to see it for yourself.",60,"Doug2_2_6")

Dialogue.New("Doug2_2_6_1_1", "Douglass", 1, "Maybe we could see it together some day? If you uh- don't mind watching it again.",60,"Doug2_2_6_1_2",true)
Dialogue.New("Doug2_2_6_1_2", "Lorelai", 1, "Yeah! Honestly I would love to see what you think about it. ",60,"Doug2_2_6_1_3",true)
Dialogue.New("Doug2_2_6_1_3", "Lorelai", 1, "I would definitely say it's a creative kind of movie. You know?",60,"Doug2_2_6_1_4",true)
Dialogue.New("Doug2_2_6_1_4", "Douglass", 1, "..Yeah. Haha.",60,"Doug3_1")

Dialogue.New("Doug2_2_6_2_1", "Douglass", 1, "Maybe we could see it together some day? If you uh- don't mind watching it again.",60,"Doug2_2_6_2_2",true)
Dialogue.New("Doug2_2_6_2_2", "Lorelai", 1, "Oh. Yeah, uh. Maybe.",60,"Doug2_2_6_2_3",true)
Dialogue.New("Doug2_2_6_2_3", "Douglass", 1, "..Alright.",60,"Doug3_1")

Dialogue.New("Doug2_3_1", "Douglass", 1, "You film a lot of stuff? What kind of things do you uh.. film?",60,"Doug2_3_2",true)
Dialogue.New("Doug2_3_2", "Lorelai", 1, "Honestly it's kinda a lot of slice of life stuff I guess. But I do a little horror too.",60,"Doug2_3_3",true)
Dialogue.New("Doug2_3_3", "Douglass", 1, "Horror? I can't really watch horror-",60,"Doug2_3_4",true)
Dialogue.New("Doug2_3_4", "Lorelai", 1, "You scared?",60,"Doug3_1")

Dialogue.New("Doug2_3_4_1_1", "Douglass", 1, "Uh.. no. not at all. Just uh.. Most are just uh- too tame.. You know?",60,"Doug2_3_4_1_2",true)
Dialogue.New("Doug2_3_4_1_2", "Lorelai", 1, "Uhm. I guess.",60,"Doug3_1")

Dialogue.New("Doug2_3_4_2_1", "Douglass", 1, "Yeah.. yeah I uh- kinda am. Can't really handle gore that much.",60,"Doug2_3_4_2_2",true)
Dialogue.New("Doug2_3_4_2_2", "Lorelai", 1, "Aw. That's kinda cute.",60,"Doug2_3_4_2_3",true)
Dialogue.New("Doug2_3_4_2_3", "Douglass", 1, "..Really?",60,"Doug2_3_4_2_4",true)
Dialogue.New("Doug2_3_4_2_4", "Lorelai", 7, "Least you admitted it, you know? Scared men are hot.",60,"Doug2_3_4_2_5",true)
Dialogue.New("Doug2_3_4_2_5", "Douglass", 1, "..Uh... Yeah.",60,"Doug3_1")

Dialogue.New("Doug2_4_1", "Douglass", 1, "So.. Why are you a chemistry minor?",60,"Doug2_4_2",true)
Dialogue.New("Doug2_4_2", "Douglass", 1, "I mean it's pretty different from film.",60,"Doug2_4_3",true)
Dialogue.New("Doug2_4_3", "Lorelai", 1, "Honestly I'm just really interested in SFX makeup.",60,"Doug2_4_4",true)
Dialogue.New("Doug2_4_4", "Lorelai", 1, "And I feel like learning about how to formulate different types of special effects make up-",60,"Doug2_4_5",true)
Dialogue.New("Doug2_4_5", "Lorelai", 1, "is just really cool to me. So in a way I feel like it's pretty similar.",60,"Doug2_4_6",true)
Dialogue.New("Doug2_4_6", "Douglass", 1, "Oh, really? Wow, that uh- that's pretty cool. I mean I watch a lot of movies. And films.",60,"Doug3_1",true)